### ISSUE TITLE
Certain column names appear to cause problems in tiling task SQL

### ISSUE THREAD

**Issue by robharper** [unchartedsoftware/aperture-tiles#192]
In another code base we had an issue where certain column names would break spark SQL selects. Upon fixing that issue I now see the following exception in tiles and would assume it's caused by the same thing - the need to escape all column and table names in generated sql statements:

```
org.apache.spark.sql.AnalysisException: missing \\' at 'FROM' near '<EOF>'; line 1 pos 15
	at org.apache.spark.sql.hive.HiveQl$.createPlan(HiveQl.scala:254)
	at org.apache.spark.sql.hive.ExtendedHiveQlParser$$anonfun$hiveQl$1.apply(ExtendedHiveQlParser.scala:41)
	at org.apache.spark.sql.hive.ExtendedHiveQlParser$$anonfun$hiveQl$1.apply(ExtendedHiveQlParser.scala:40)
	at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:136)
	at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:135)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1$$anonfun$apply$2.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1$$anonfun$apply$2.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$Failure.append(Parsers.scala:202)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$$anon$2$$anonfun$apply$14.apply(Parsers.scala:891)
	at scala.util.parsing.combinator.Parsers$$anon$2$$anonfun$apply$14.apply(Parsers.scala:891)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at scala.util.parsing.combinator.Parsers$$anon$2.apply(Parsers.scala:890)
	at scala.util.parsing.combinator.PackratParsers$$anon$1.apply(PackratParsers.scala:110)
	at org.apache.spark.sql.catalyst.AbstractSparkSQLParser.apply(AbstractSparkSQLParser.scala:38)
	at org.apache.spark.sql.hive.HiveQl$$anonfun$3.apply(HiveQl.scala:138)
	at org.apache.spark.sql.hive.HiveQl$$anonfun$3.apply(HiveQl.scala:138)
	at org.apache.spark.sql.SparkSQLParser$$anonfun$org$apache$spark$sql$SparkSQLParser$$others$1.apply(SparkSQLParser.scala:96)
	at org.apache.spark.sql.SparkSQLParser$$anonfun$org$apache$spark$sql$SparkSQLParser$$others$1.apply(SparkSQLParser.scala:95)
	at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:136)
	at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:135)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1$$anonfun$apply$2.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1$$anonfun$apply$2.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$Failure.append(Parsers.scala:202)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$$anon$2$$anonfun$apply$14.apply(Parsers.scala:891)
	at scala.util.parsing.combinator.Parsers$$anon$2$$anonfun$apply$14.apply(Parsers.scala:891)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at scala.util.parsing.combinator.Parsers$$anon$2.apply(Parsers.scala:890)
	at scala.util.parsing.combinator.PackratParsers$$anon$1.apply(PackratParsers.scala:110)
	at org.apache.spark.sql.catalyst.AbstractSparkSQLParser.apply(AbstractSparkSQLParser.scala:38)
	at org.apache.spark.sql.hive.HiveQl$.parseSql(HiveQl.scala:234)
	at org.apache.spark.sql.hive.HiveContext$$anonfun$sql$1.apply(HiveContext.scala:101)
	at org.apache.spark.sql.hive.HiveContext$$anonfun$sql$1.apply(HiveContext.scala:101)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.sql.hive.HiveContext.sql(HiveContext.scala:101)
	at com.oculusinfo.tilegen.datasets.StaticTilingTask$StaticTilingTaskProcessingStrategy.getData(TilingTask.scala:365)
	at com.oculusinfo.tilegen.datasets.StaticProcessingStrategy.<init>(ProcessingStrategy.scala:65)
	at com.oculusinfo.tilegen.datasets.StaticTilingTask$StaticTilingTaskProcessingStrategy.<init>(TilingTask.scala:357)
	at com.oculusinfo.tilegen.datasets.StaticTilingTask.initialize(TilingTask.scala:353)
	at com.oculusinfo.tilegen.datasets.TilingTask$.withTilingTags$1(TilingTask.scala:112)
	at com.oculusinfo.tilegen.datasets.TilingTask$.withValueTags$1(TilingTask.scala:114)
	at com.oculusinfo.tilegen.datasets.TilingTask$.apply(TilingTask.scala:118)
...
```

**Comment by cdbethune** [comment]
@sylvainJE - I merged 5cc1cc8ce19c32bbcafdd6d69540a7544d615858 as part of #238 for @robharper, and cherry-picked it into develop without comitting.  It was failing test cases - can you look into that, and also see if there other spots in our code that need similar adjustment?
