### ISSUE TITLE
Julia example does not work

### ISSUE THREAD

**Issue by rustandruin** [unchartedsoftware/aperture-tiles#259]
The Julia example does not work, e.g. 

```
$SPARK_HOME/bin/spark-submit --class com.oculusinfo.tilegen.examples.datagen.JuliaSetGenerator --master local[2] ~/aperture-tiles/tile-generation/build/libs/tile-generation-0.6-SNAPSHOT-cdh4.6.0-assembly.jar -d ~/aperture-tiles/tile-packaging/src/examples/julia-base.bd ~/aperture-tiles/tile-packaging/src/examples/julia-tiling.bd
```
gives me the error 
```
Exception in thread "main" java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:313)
        at scala.None$.get(Option.scala:311)
        at com.oculusinfo.tilegen.util.KeyValueArgumentSource.getNumeric(KeyValueArgumentSource.scala:285)
        at com.oculusinfo.tilegen.util.KeyValueArgumentSource.getDouble(KeyValueArgumentSource.scala:374)
        at com.oculusinfo.tilegen.examples.datagen.JuliaSetGenerator$.main(juliagen.scala:49)
        at com.oculusinfo.tilegen.examples.datagen.JuliaSetGenerator.main(juliagen.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:569)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:166)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:189)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:110)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

The only thing I did other than follow the vanilla instructions was to edit julia-base.bd to set
```
oculus.binning.source.location=/root/datasets/julia
```
since that's where my output from the generation step is.

**Comment by mecrouch** [comment]
It looks like there's an error in the command you're using to execute the tile generation job. You're invoking the JuliaSetGenerator class, which is only used to create the Julia set data. Instead, you want to use the CSVBinner class, which converts the Julia set data into a pyramid of tiles for your visual analytic. 

So, you want to replace this part of your command:

```bash
com.oculusinfo.tilegen.examples.datagen.JuliaSetGenerator
```

With:

```bash 
com.oculusinfo.tilegen.examples.apps.CSVBinner
```

Then your complete command should look like this:

```bash
$SPARK_HOME/bin/spark-submit --class com.oculusinfo.tilegen.examples.apps.CSVBinner --master local[2] ~/aperture-tiles/tile-generation/build/libs/tile-generation-0.6-SNAPSHOT-cdh4.6.0-assembly.jar -d ~/aperture-tiles/tile-packaging/src/examples/julia-base.bd ~/aperture-tiles/tile-packaging/src/examples/julia-tiling.bd
```
