### ISSUE TITLE
Julia Set Sample Run Error.  java.lang.NoSuchFieldError: IS_SECURITY_ENABLED

### ISSUE THREAD

**Issue by coguin** [unchartedsoftware/aperture-tiles#320]
Hi, I runed the Julia Set Aperture Tiles Sample according to the tutorail. But when I run the ../../gradlew jettyrun,  It always occured errors.  And ../../gradlew install is OK. 

The details:
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/zhaoj/.gradle/wrapper/dists/gradle-2.8-bin/4rsda7i357a5ogdj89yq8dntm/gradle-2.8/lib/gradle-core-2.8.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/zhaoj/github/aperture-tiles/tile-examples/julia-demo/build/exploded/WEB-INF/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/zhaoj/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.7.5/6edffc576ce104ec769d954618764f39f0f0f10d/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
failed jsp: java.lang.NoSuchFieldError: IS_SECURITY_ENABLED
failed org.gradle.api.plugins.jetty.internal.JettyPluginWebAppContext@628115aa{/julia-demo,/home/zhaoj/github/aperture-tiles/tile-examples/julia-demo/build/exploded}: java.lang.NoSuchFieldError: IS_SECURITY_ENABLED
failed ContextHandlerCollection@acf45f6: java.lang.NoSuchFieldError: IS_SECURITY_ENABLED
failed HandlerCollection@6e121311: java.lang.NoSuchFieldError: IS_SECURITY_ENABLED
Error starting handlers
java.lang.NoSuchFieldError: IS_SECURITY_ENABLED
	at org.apache.jasper.compiler.JspRuntimeContext.<init>(JspRuntimeContext.java:197)
	at org.apache.jasper.servlet.JspServlet.init(JspServlet.java:150)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1272)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:489)
	at org.gradle.api.plugins.jetty.internal.JettyPluginWebAppContext.doStart(JettyPluginWebAppContext.java:112)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerCollection.doStart(HandlerCollection.java:152)
	at org.mortbay.jetty.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:156)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerCollection.doStart(HandlerCollection.java:152)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.gradle.api.plugins.jetty.internal.Jetty6PluginServer.start(Jetty6PluginServer.java:111)
	at org.gradle.api.plugins.jetty.AbstractJettyRunTask.startJettyInternal(AbstractJettyRunTask.java:238)
	at org.gradle.api.plugins.jetty.AbstractJettyRunTask.startJetty(AbstractJettyRunTask.java:191)
	at org.gradle.api.plugins.jetty.AbstractJettyRunTask.start(AbstractJettyRunTask.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)

I stucked in the problems several days... And really don't know how to solve it ...

**Comment by cdbethune** [comment]
Aperture Tiles is no longer under active development, and has been replaced by Salt, a more focused library based on the same principles.  Info and examples to get you started are provided at http://unchartedsoftware.github.io/salt-core.  Some additional capabilities that were part of Aperture Tiles, but were excluded from Salt, are available through https://github.com/unchartedsoftware/salt-tiling-contrib.

If there is something in Aperture Tiles that is not part of either of those repositories that is of interest, let us know and we can see about including it.

If you do still want to build ApertureTiles, I would suggest verifying that you are building off of the v0.7.1 tag.  Dependencies in develop branch may have grown stale over time as some versions are not pinned.

**Comment by cocokeke** [comment]
Thank you very much. It helps me a lot.

**Comment by cocokeke** [comment]
En. I have changed to v0.7.1, but the error still not be solved .. And I still want to build Aperture Tiles, so could you please give me more infomation about how to sovle it ? I have searched a lot , but all can't fix the problem.   
Thanks in advance.
